name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php7.0 php7.0-cli php7.0-common php7.0-curl php7.0-gd php7.0-json php7.0-mbstring php7.0-mysql php7.0-opcache php7.0-readline php7.0-xml php7.0-zip
          curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
          sudo chmod +x /usr/local/bin/composer
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Build
        run: |
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          npm install && npm run production
      - name: Deploy
        uses: easingthemes/ssh-deploy@v3.0.0
        with:
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          args: "-rltgoDzvO --delete"
          local_path: "."
          remote_path: "/var/www/html/hello-world"
          host: 3.104.35.2
      - name: Restart Services
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.104.35.2 "sudo service apache2 restart"
          ssh -o StrictHostKeyChecking=no ubuntu@3.104.35.2 "echo 'Hello, world!'"

